jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: admin123
tool:
  git:
    installations:
    - home: "/bin/git"
      name: "Default"
  maven:
    installations:
    - name: "Maven 3"
      home: "/bin/maven3"
      properties:
      - installSource:
          installers:
            - maven:
                id: "3.5.4"
unclassified:
  location:
    url: http://loclhost:8080/
  githubpluginconfig:
    configs:
      - name: "InHouse GitHub EE"
        apiUrl: "http://loclhost:80/"
        #credentialsId: "[GitHubEEUser]"
        manageHooks: true

jobs:
  - script: >
        pipeline {
            agent any
            stages {
                stage('Test') {
                    steps {
                        sh 'echo "Fail!"; exit 1'
                    }
                }
            }
            post {
                always {
                    echo 'This will always run'
                }
                success {
                    echo 'This will run only if successful'
                }
                failure {
                    echo 'This will run only if failed'
                }
                unstable {
                    echo 'This will run only if the run was marked as unstable'
                }
                changed {
                    echo 'This will run only if the state of the Pipeline has changed'
                    echo 'For example, if the Pipeline was previously failing but is now successful'
                }
            }
        }