jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: admin123
tool:
  git:
    installations:
    - home: "/bin/git"
      name: "Default"
  maven:
    installations:
    - name: "Maven 3"
      home: "/bin/maven3"
      properties:
      - installSource:
          installers:
            - maven:
                id: "3.5.4"
unclassified:
  location:
    url: http://loclhost:8080/
  githubpluginconfig:
    configs:
      - name: "InHouse GitHub EE"
        apiUrl: "http://loclhost:80/"
        #credentialsId: "[GitHubEEUser]"
        manageHooks: true

jobs:
  - script: >
        job('Job-DSL-Hello-World-Job') {
            scm {
                git('git://github.com/oveits/java-maven-junit-helloworld')
            }
            triggers {
                scm('H/15 * * * *')
            }
            steps {
                maven('-e clean test')
            }
        }