jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: admin123
  globalNodeProperties:
  - envVars:
      env:
      - key: MAVEN_HOME
        value: /var/jenkins_home/apache-maven-3.8.1/
      - key: M2_HOME
        value: /var/jenkins_home/apache-maven-3.8.1/
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  maven:
    installations:
    - name: "Default"
      home: "/var/jenkins_home/apache-maven-3.8.1/"
      properties:
      - installSource:
          installers:
            - maven:
                id: "3.5.4"
unclassified:
  location:
    url: http://loclhost:8080/
  githubpluginconfig:
    configs:
      - name: "InHouse GitHub EE"
        apiUrl: "http://loclhost:80/"
        #credentialsId: "[GitHubEEUser]"
        manageHooks: true
  gitscm:
    globalConfigName: jenkins
    globalConfigEmail: jenkins@domain.local
    createAccountBasedOnEmail: true

jobs:
  - script: >
        job('Job-DSL-Hello-World-Job') {
            scm {
                git('git://github.com/oveits/java-maven-junit-helloworld')
            }
            triggers {
                scm('H/15 * * * *')
            }
            steps {
              maven(' clean test')
            }
            
        }
  - script: >
      multibranchPipelineJob('configuration-as-code') {
          branchSources {
              git {
                  id = 'configuration-as-code'
                  remote('https://github.com/jenkinsci/configuration-as-code-plugin.git')
              }
          }
      }