jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: admin123
tool:
  git:
    installations:
    - home: "/bin/git"
      name: "Default"
  maven:
    installations:
    - name: "Maven 3"
      home: "/bin/maven3"
      properties:
      - installSource:
          installers:
            - maven:
                id: "3.5.4"
unclassified:
  location:
    url: http://loclhost:8080/
  githubpluginconfig:
    configs:
      - name: "InHouse GitHub EE"
        apiUrl: "http://loclhost:8080/"
        #credentialsId: "[GitHubEEUser]"
        manageHooks: true

jobs:
  - script: >
        pipeline {
            agent { docker { image 'maven:3.3.3' } }
                stages {
                    stage('build') {
                        steps {
                            sh 'mvn --version'
                        }
                    }
                }
            }